name: launcher1
description: Launcher App
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.6+7

environment:
  sdk: '>=3.1.5 <4.0.0'


dependencies:
  android_intent_plus: ^4.0.3
  auto_route: ^7.8.4
  battery_plus: ^4.1.0
  collection: ^1.17.2
  device_apps: ^2.2.0
  device_policy_manager: ^0.0.1
  dio: ^5.3.3
  dpad_container: ^2.0.4
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9
  get_it: ^7.6.4
  injectable: ^2.3.2
  install_plugin: ^2.1.0
  intl: ^0.18.1
  package_info_plus: ^4.2.0
  path_provider: ^2.1.1
  permission_handler: ^11.0.1


dev_dependencies:
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.6
  # https://dhruvnakum.xyz/fluttergen-manage-assets-like-a-pro
  flutter_gen_runner: ^5.3.2
  flutter_lints: ^2.0.3
  flutter_localizations:
    sdk: flutter
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.4.1

flutter:
  assets:
    - assets/images/